---
- name: Clean previous Kismet installation and generated files.
  include: clean.yml
  when: ({{ kismet_rpi_wardriving_clean }})

- name: Install and configure Kismet Server.
  include: install.yml
  when: ({{ kismet_rpi_wardriving_install }})

- name: Run Kismet Server as systemd service.
  include: run.yml
  when: ({{ kismet_rpi_wardriving_run }})
